apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    app: my-nginx
  ports:
  - protocol: TCP
    port: 77
    targetPort: 7777
#  type: LoadBalancer  # Expose as a LoadBalancer (suitable for cloud environments)
  type: NodePort  # Expose as a LoadBalancer (suitable for cloud environments)